version: '3.4'
services:
  mjolnir01:
    image: mjolnir:latest
    container_name: mjolnir01
    environment:
      - KAFKA_BROKERS=kafka01:9092
      - ELASTIC_HOSTS=es01:9200
      - BULK_TOPIC=mjolnir_bulk
      - SWIFT_TOPIC=mjolnir_swift
      - KAFKA_GROUP_ID=analytics_integration
      - ST_AUTH_VERSION=1
      - ST_AUTH=http://swift01:8080/auth/v1.0
      - ST_USER=test:tester
      - ST_KEY=testing
    depends_on:
      - es01
      - kafka01
      - swift01
    volumes:
      - mwdata01:/data
      - ./conf/mediawiki:/conf:ro
    ports:
        - 8808:80
    depends_on:
      - es01
      - mysql01
  mysql01:
    image: mysql:5.7.4
    container_name: mysql01
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysqldata03:/var/lib/mysql
  es01:
    build:
        context: ./
        dockerfile: ./Dockerfile-wmfelastic
    container_name: es01
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  swift01:
    image: bouncestorage/swift-aio:latest
    container_name: swift01
    ports:
      - 8080:8080
    volumes:
      - swiftdata01:/swift/nodes
  zookeeper01:
    image: bitnami/zookeeper:3
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka01:
      image: bitnami/kafka:latest
      container_name: kafka01
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper01
  cdh01:
      image: cloudera/quickstart:latest
      privileged: true
      container_name: cdh01
      hostname: quickstart.cloudera
      command: /usr/bin/docker-quickstart
      ports:
          - 8888:8888 # Hue
          - 8088:8088 # Yarn RM
      tty: true
      stdin_open: true

volumes:
  esdata01: {}
  mwdata01: {}
  mysqldata03: {}
  swiftdata01: {}
